### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by auer-kk** [GiovanniSalmeri/yellow-filelist#3]
1:
`FilelistShowType`

doesn't work

2:
> extensions of files to list, * for all extensions; wrap multiple extensions into quotes

`[filelist docs "pdf odt"]`
`[filelist docs * 0]`

both don't work

**Comment by GiovanniSalmeri** [comment]
Thank you very much for alerting me!

Now `FilelistShowType` should work (I have updated `filelist.php` and `filelist.css`).

As regards the second problem, the error was in the README file: the correct syntax is `[filelist docs pdf,odt]` and `[filelist docs - 0]`.

Some time ago I rewrote the extension and apparently I didn't doublecheck all. Sorry!

**Comment by auer-kk** [comment]
Everything works now. Thanks a lot!
